# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
  - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: fetch
      run: git fetch origin
    - name: merge to master
      run: git merge master
    - name: merge to main
      run: git checkout origin/master && git merge main && git checkout main && git push origin
